### ISSUE TITLE
The result is different

### ISSUE THREAD

**Issue by xiaoluzaina** [JianZhou1212/interaction-safety-aware-motion-planning#2]
Hello, I am very interested in your work, but when I ran the main program in the case, I found that the MP4 video obtained was different from the example. There was no trajectory information planned by EV. The EV in other sub-pictures The information is also missing. When debugging, I found that the state predictions for EV in X_State were all zero. I tried to modify it, but failed. Where does the problem occur?

**Comment by JianZhou1212** [comment]
Hi, thanks for your interest! I am on vacation now so I can not test the code on my work computer. If you get EV's state prediction as zeor while the code was running without any errors/warning reported, you may try to comment out "ipopt.linear_solver": "ma57" in the file ISA_MPC (and also other places). ( As I guess the problem was that you did not successfully install the HSL linear solver in Casadi.) I will be back to uni. on July 31, so if you still meet issues you can email me then we can look at the details. Good luck!

**Comment by xiaoluzaina** [comment]
Thank you for your reply, the problem is as you said, I did not successfully install the HSL linear solver in Casadi. And this problem has been solved, thank you again.
